### PR TITLE
Move FreeBSD CI to Travis, test on v1.0, 1.4 and nightly only

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by mileslucas** [comment]
has some conflicts with #15 I can just toss my CI changes and rebase after this pushes? otherwise I can make changes in that PR, too.

**Comment by giordano** [comment]
Good catch!  I've taken the remaining changes to travis in #15, so that this can be a pure CI pull request and #15 will become a pure documentation pull request.

**Comment by mileslucas** [comment]
sounds good 👍

**Comment by giordano** [comment]
It looks like there are some warnings from Polynomials:
```
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Polynomials.PolyCompat.Poly(::Array{Float64,1}) at Poly.jl:26
└ @ Polynomials.PolyCompat ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
┌ Warning: Use of `Poly` from v1.0 forward will require `using Polynomials.PolyCompat`
│   caller = Type at Poly.jl:26 [inlined]
└ @ Core ~/.julia/packages/Polynomials/ghqdF/src/polynomials/Poly.jl:26
```

**Comment by mileslucas** [comment]
Nothing to worry about for right now (I actually wrote ~95% of the recent changes to the Polynomials library). The changes required are `Poly` -> `Polynomial`. Otherwise, we can drop the Polynomials.jl dependency and use `@evalpoly`, too, since that is just as fast (sometimes faster) than the Polynomials.jl implementation of Horner's algorithm.

**Comment by giordano** [comment]
Yeah, just for evaluating polynomials with known coefficients `@evalpoly` is good enough.  `Polynomials.jl` is nice, but probably more useful if you want to do something more with the polynomial, or you don't know the number of coefficients in advance (i.e., they're put programmatically in a tuple/vector) and the macro can't be used (even though now in Julia v1.4 there is a function for this).

**Pull request merged**
